# Generated by Django 4.0.5 on 2022-08-26 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driverjob', '0003_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(null=True, upload_to='')),
                ('applydate', models.DateField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driverjob.driveruser')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driverjob.job')),
            ],
        ),
    ]
