# Generated by Django 4.0.5 on 2022-10-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverjob', '0004_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveruser',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driveruser',
            name='yearsofexperience',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='driveruser',
            name='yearsoflicense',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='cartype',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
